main/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, CustomLoginView, LogoutView, TaskReorder, RegisterPage, CategoryCreate, CategoryUpdate, CategoryDelete

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),

    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task/create', TaskCreate.as_view(), name='task-create'),
    path('task/update/<int:pk>', TaskUpdate.as_view(), name='task-update'),
    path('task/delete/<int:pk>', DeleteView.as_view(), name='task-delete'),
    path('task/reorder/', TaskReorder.as_view(), name='task-reorder'),

    path('category/add/', CategoryCreate.as_view(), name='category-add'),
    path('category/update/<int:pk>', CategoryUpdate.as_view(), name='category-update'),
    path('category/delete/<int:pk>', CategoryDelete.as_view(), name='category-delete')
]

todo_app/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model): # Таблица категория которая наследует models.Model
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, verbose_name='Название категории') #varchar.Нам потребуется только имя категории
    class Meta:
        verbose_name = ("Category") # человекочитаемое имя объекта
        verbose_name_plural = ("Categories")  #человекочитаемое множественное имя для Категорий
    def __str__(self):
        return self.name  # __str__ применяется для отображения объекта в интерфейсе

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Имя пользователя')
    title = models.CharField(max_length=200, verbose_name='Название задачи')
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name='Описание')
    complete = models.BooleanField(default=False, verbose_name='Выполнена?')
    create = models.DateTimeField(default=timezone.now)  # Изменено здесь
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='Категория')
    due_date = models.DateField(default=timezone.now)  # Изменено здесь

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete', '-create']

main/forms.py
from django import forms

class PositionForm(forms.Form):
    position = forms.CharField()

main/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, FormView
from django.urls import reverse_lazy
from .models import Task, Category
from .forms import PositionForm

from django.db import transaction

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

def get_default_category(user):
    category, created = Category.objects.get_or_create(name='Нет категории', user=None)
    category.user = user
    category.save()
    return category

class CustomLoginView(LoginView):
    template_name = 'main/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):  
        return reverse_lazy('tasks')

class RegisterPage(FormView):
    template_name = 'main/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage, self).get(*args, **kwargs)

class TaskList(LoginRequiredMixin,ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or '' # запрашивается из поля
        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__contains=search_input)

        context['search_input'] = search_input # после выполнения не оставляет поле пустым, а последним запросом

        return context

class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task # забирает модель из models
    context_object_name = 'task' 
    template_name = 'main/task.html' # желаемое имя шаблона

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'category', 'complete']
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        categories = Category.objects.filter(user=self.request.user)

        if categories.exists():
            default_category = None
            form.instance.category = default_category

        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'category', 'complete']
    success_url = reverse_lazy('tasks')

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks')

class TaskReorder(View):
    def post(self, request):
        form = PositionForm(request.POST)

        if form.is_valid():
            positionList = form.cleaned_data["position"].split(',')

            with transaction.atomic():
                self.request.user.set_task_order(positionList)

        return redirect(reverse_lazy('tasks'))

class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['name']
    template_name = 'main/category_form.html'
    success_url = reverse_lazy('tasks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.filter(user=self.request.user)
        context['form_title'] = 'Добавить категорию'
        return context
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['name']
    template_name = 'main/category_update.html'
    success_url = reverse_lazy('tasks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.filter(user=self.request.user)
        context['form_title'] = 'Изменить категорию'
        return context


class CategoryDelete(DeleteView, LoginRequiredMixin):
    model = Category
    context_object_name = 'category'
    success_url = reverse_lazy('tasks')

    def delete(self, request, *args, **kwargs):
        category = self.get_object()

        tasks_with_category = Task.objects.filter(category=category)
        general_category = Category.objects.get(user=None, name='Нет категории')
        tasks_with_category.update(category=general_category)

        return super().delete(request, *args, **kwargs)

main/templates/main/login.html
{% extends 'main/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Войти</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <div class="login-form">
            {{form.as_p}}
        </div>
        <input style="margin-left: 0px;" class="button" type="submit" value="Войти">
    </form>
    <p>У вас нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a></p>
</div>

{% endblock content%}

main/templates/main/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>To Do Items</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
</head>

<body>

    <div class="container">
        {% block content %} 
        {% endblock content %}
    </div>

</body>


</html>

main/templates/main/register.html
{% extends 'main/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Регистрация</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:15px; margin-left: 0px;" class="button" type="submit" value="Зарегистрироваться">
    </form>
    <p>Существует аккаунт? <a href="{% url 'login' %}">Войти</a></p>
</div>




{% endblock content %}

main/templates/main/task.html
{% extends 'main/task_list.html' %}

{% block content %}

<h1>Task: {{task}}</h1>

{% endblock content %}

main/templates/main/task_confirm_delete.html
{% extends 'main/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Назад</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить эту задачу? <b>"{{task}}"</b> </p>
        <input style="margin-left: 0px;" class="button" type="submit" value="Удалить" />
        <a style="padding-left: 10px;" href="{% url 'tasks' %}">Отмена</a>
    </form>
</div>



{% endblock content %}

main/templates/main/task_form.html
{% extends 'main/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Назад</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input style="margin-left: 0px;" class="button" type="submit" value="Отправить">
    </form>
</div>


{% endblock content %}

main/templates/main/task_list.html
{% extends 'main/main.html' %} 
{% block content %}
{% load custom_filters %}

<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<div class="header-bar">
    <div>
        <h1 style="margin-bottom: 5px;">Привет, {{request.user|title}}</h1>
    </div>

    {% if request.user.is_authenticated %}
    <a id="logout" href="{% url 'logout' %}">Выйти</a> {% else %}
    <a href="{% url 'login' %}">Авторизоваться</a> {% endif %}
</div>

<div class="count-task">
    <h3 style="margin:0">Вы имеете {{ count }} задач{{ count|tasks_suffix }}</h3>
    <a href="{% url 'category-add' %}">Создать/Изменить категорию</a>
</div>


<div id="search-add-wrapper">
    <form method="GET" style="display: flex;">
        <input class="search-task" type='text' name='search-area' placeholder="Найдите вашу задачу: " value="{{search_input}}">
        <input class="button" type="submit" value='Найти'>
    </form>
    {% if tasks|length > 0 %}
        <a id="add-link" href="{% url 'task-create' %}">&#x2b;</a>
    {% endif %}
</div>


<!-- Hidden form. Form submits new item positions -->
<form style="display: none;" id="reorderForm" method="post" action="{% url 'task-reorder' %}">
    {% csrf_token %}
    <input type="hidden" id="positionInput" name="position">
</form>


<div id="tasklist" class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper" data-position="{{task.pk}}">
        <div class="task-title">
            {% if task.complete %}
                <div class="task-complete-icon"></div>
                <i><s><a href="{% url 'task-update' task.id %}">{{task}}</a></s></i> {% else %}
                <div class="task-incomplete-icon"></div>
                <a href="{% url 'task-update' task.id %}">{{task}}</a>
            {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'task-delete' task.id %}">&#215;</a>
            <span class="handle">&nbsp;&#10247;</span>
        </div>
    </div>

    {% empty %}
        <div style="text-align: center; padding-bottom: 10px; line-height: 1em;">
            <h3>Не имеется задач</h3>
            <h3>Создайте <a style="text-decoration: none; color: #e53935;" href="{% url 'task-create' %}">новую задачу</a> ! </h3>
        </div>
    {% endfor %}
</div>

<script>
    var taskList = document.getElementById("tasklist");
    var reorderForm = document.getElementById("reorderForm");
    var positionInput = document.getElementById("positionInput");

    let sortable = Sortable.create(taskList, {
        handle: '.handle',
        ghostClass: 'dropArea',
        chosenClass: 'selectedTask',

    });

    function reordering() {
        const rows = document.getElementsByClassName("task-wrapper");
        let pos = [];
        for (let row of rows) {
            pos.push(row.dataset.position);
        }
        console.log(pos.join(","))
        positionInput.value = pos.join(',');
        reorderForm.submit();
    }

    document.ondrop = reordering
</script>

{% endblock content %}